branches:
  only:
  - master
  - dev
  - travis
language: go
node_js:
- 1.11.x
script:
- echo "hi"
- go get -u github.com/alecthomas/gometalinter
- gometalinter --install
- cd ../../
- pwd
- gometalinter ../src/2018_2_YetAnotherGame/ApiMS/controllers/
before_install:
- openssl aes-256-cbc -K $encrypted_43b03c082b97_key -iv $encrypted_43b03c082b97_iv
  -in 2018_2_YetAnotherGame_id_rsa.pem.enc -out ./2018_2_YetAnotherGame_id_rsa.pem
  -d

